// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class canged_UserId_to_string_in_documents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(canged_UserId_to_string_in_documents));
        
        string IMigrationMetadata.Id
        {
            get { return "201712050840338_canged_UserId_to_string_in_documents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
