// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Altered_Activitycs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altered_Activitycs));
        
        string IMigrationMetadata.Id
        {
            get { return "201712011054172_Altered_Activitycs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
